batch_size: 32
epochs: 20 ## 1000
eval_every_n_epochs: 4 ## 5s
fine_tune_from: Jan16_02-27-36_edu-GPU-Linux
log_every_n_steps: 2
learning_rate: 1e-4
weight_decay: 1e-4
fp16_precision: False
truncation: True

model:
  out_dim: 512
  res_base_model: "resnet50"
  bert_base_model: 'emilyalsentzer/Bio_ClinicalBERT'
  freeze_layers: [0,1,2,3,4,5,6,7,8,9,10,11]
  do_lower_case: False
  
train_dataset:
  s: 1
  input_shape: (224,224,3)
  num_workers: 1 ## 4
  csv_file: '/dshome/ddualab/jiwon/skin_cancer_fairness/data/f_b_train_df.csv'
  img_root_dir: '/dshome/ddualab/jiwon/skin_cancer_fairness/data/skin_cancer_images'
  img_path_col: 'img_id' # index for the image path column in the CSV dataframe.
  text_root_dir: '/dshome/ddualab/jiwon/skin_cancer_fairness/data/f_b_train_df.csv'
  # text_col1: 'lesion_description'
  # text_col2: 'fitzpatrick_description'
  label_col: 'label'
  fitz_scale_col : 'fitzpatrick_scale'

test_dataset:
  s: 1
  input_shape: (224,224,3)
  num_workers: 1 ## 4
  csv_file: '/dshome/ddualab/jiwon/skin_cancer_fairness/data/f_b_test_df.csv'
  img_root_dir: '/dshome/ddualab/jiwon/skin_cancer_fairness/data/skin_cancer_images'
  img_path_col: 'img_id' # index for the image path column in the CSV dataframe.
  text_root_dir: '/dshome/ddualab/jiwon/skin_cancer_fairness/data/f_b_test_df.csv'
  # text_col1: 'lesion_description'
  # text_col2: 'fitzpatrick_description'
  label_col: 'label'
  fitz_scale_col : 'fitzpatrick_scale'

cl_loss:
  temperature: 0.1
  use_cosine_similarity: True
  alpha_weight: 0.75

### BERT Models
# emilyalsentzer/Bio_ClinicalBERT
# bert-base-uncased
# distilbert-base-nli-mean-tokens
# distilbert-base-multilingual-cased
# distiluse-base-multilingual-cased-v2
# sentence-transformers/distilbert-base-nli-stsb-mean-tokens
# sentence-transformers/xlm-r-100langs-bert-base-nli-stsb-mean-tokens #good
# cross-encoder/stsb-roberta-base
# sentence-transformers/paraphrase-xlm-r-multilingual-v1 #good
# Portuguese: neuralmind/bert-base-portuguese-cased