batch_size: 32 # 32
epochs: 100
learning_rate: 0.0001
weight_decay: 1e-4
T_0: 2
T_mult: 2
eta_max: 0.0001
T_up: 1
gamma: 1
fp16_precision: False
truncation: True
# pretrained: True
classes: 6
fitz_classes: 4

pad_img_root_dir: '/dshome/ddualab/jiwon/skin_cancer_fairness/data/PAD_UFES_20_images'
fitz17_img_root_dir: '/dshome/ddualab/jiwon/skin_cancer_fairness/data/fitzpatrick17_images'

train_csv: '/dshome/ddualab/jiwon/skin_cancer_fairness/data/in_m_train_df.csv' # in_m_train_df.csv # out_fitz12_m_df.csv
test_csv: '/dshome/ddualab/jiwon/skin_cancer_fairness/data/in_m_test_df.csv' # in_m_test_df.csv # out_fitz34_m_df.csv

model:
  out_dim: 512
  res_base_model: 'resnet50'
  bert_base_model: 'emilyalsentzer/Bio_ClinicalBERT'  
  freeze_layers: [0,1,2,3,4,5,6,7,8,9,10,11]
  do_lower_case: False
  
dataset:
  s: 1
  input_shape: (224,224,3)
  num_workers: 1 
  # img_root_dir: '/dshome/ddualab/jiwon/skin_cancer_fairness/data/PAD_UFES_20_images'
  img_path_col: 'img_id' 
  text_col1: 'lesion_description'
  text_col2: 'fitzpatrick_description'
  label_col: 'label'
  fitz_scale_col : 'fitzpatrick_scale'

cl_loss:
  temperature: 0.1
  use_cosine_similarity: True
  alpha_weight: 0.75

