batch_size: 32
epochs: 100
learning_rate: 0.0001
weight_decay: 1e-4
T_0: 2
T_mult: 2
eta_max: 0.0001
T_up: 1
gamma: 1
fp16_precision: False
truncation: True
# pretrained: True
classes: 2
fitz_classes: 2

pad_img_root_dir: '/dshome/ddualab/jiwon/skin_cancer_fairness/data/PAD_UFES_20_images'
fitz17_img_root_dir: '/dshome/ddualab/jiwon/skin_cancer_fairness/data/fitzpatrick17_images'

train_csv: '/dshome/ddualab/jiwon/skin_cancer_fairness/data/out_fitz12_b_df.csv' # out_fitz12_m_df.csv # in_m_train_df.csv
test_csv: '/dshome/ddualab/jiwon/skin_cancer_fairness/data/out_fitz34_b_fitz17_test_only_df.csv' # out_fitz34_m_df.csv # in_m_train_df.csv

model:
  out_dim: 768
  bert_base_model: 'emilyalsentzer/Bio_ClinicalBERT'
  freeze_layers: [0,1,2,3,4,5,6,7,8,9,10,11]
  do_lower_case: False
  
dataset:
  s: 1
  input_shape: (224,224,3)
  num_workers: 1 ## 4
  # img_root_dir: '/dshome/ddualab/jiwon/skin_cancer_fairness/data/skin_cancer_images'
  img_path_col: 'img_id' 
  label_col: 'label'
  fitz_scale_col : 'fitzpatrick_scale'



